<a href="https://colab.research.google.com/github/Triveni1349/AIML-LAB/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
friuts=["apple","cherry","mango"]
print(friuts)

['apple', 'cherry', 'mango']


In [3]:
import pandas as pd
friuts=["mango","cherry","apple"]
print(friuts)

['mango', 'cherry', 'apple']


In [4]:
import numpy as np
numbers=np.array([1,2,3,4,5])
print(numbers)

[1 2 3 4 5]


In [6]:
import pandas as pd
fruits=["apple","banana","cherry"]
print(type(fruits))

<class 'list'>


In [7]:
import numpy as np
numbers=np.array([9,8,7,6,5])
print(type(numbers))

<class 'numpy.ndarray'>


In [11]:
import numpy as np
num1=np.array([1,2,3])
num2=np.array([4,5,6])
print(num1*num2)
print(num1/num2)
print(num1**2)
print(num2**2)

[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[16 25 36]


In [18]:
import numpy as np
array1 = np.array([1,3,4])
array2 = np.array([5,7,8])
result = np.add(array1,array2)
print("Addition of two arrays")
print(result)

Addition of two arrays
[ 6 10 12]


In [19]:
import numpy as np
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
sin_x = np.sin(my_array)
print(f"sin({my_array}) = {sin_x}")
log_x = np.log(x)
print(f"log({my_array}) = {log_x}")
log2_x = np.log2(my_array)
print(f"log2({my_array}) = {log2_x}")
exp_x = np.exp(my_array)
print(f"exp({my_array}) = {exp_x}")

sin([1 2 3 4 5]) = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


NameError: name 'x' is not defined

In [22]:
import numpy as np
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
sin_x = np.sin(my_array)
print(f"sin({my_array}) = {sin_x}")
log_x = np.log(my_array)
print(f"log({my_array}) = {log_x}")
log2_x = np.log2(my_array)
print(f"log2({my_array}) = {log2_x}")
exp_x = np.exp(my_array)
print(f"exp({my_array}) = {exp_x}")

sin([1 2 3 4 5]) = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log([1 2 3 4 5]) = [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2([1 2 3 4 5]) = [0.         1.         1.5849625  2.         2.32192809]
exp([1 2 3 4 5]) = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
